version: "3"

services:
  app:
    build: .
    environment: 
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      # Puedes usar de mis puestos 3000 a 3010 
      - "3000-3010:3000"
    volumes:
      - c:/OwnerGit/docker:/usr/src
      # Esto no me lo tockes papu!
      - /usr/src/node_modules

  db:
    image: mongo
